stages:
  - test
  - build

variables:
  FLUTTER_CHANNEL: stable
  FLUTTER_VERSION: 3.22.2
  FLUTTER_PATH: "$HOME/flutter"

before_script:
  - |
    if [ "$(uname)" == "Darwin" ]; then
      if ! command -v brew &>/dev/null; then
        echo "Homebrew not found, installing..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      fi
      brew update
      brew install curl git unzip xz libglu
    else
      apt-get update && apt-get install -y curl git unzip xz-utils libglu1-mesa
    fi
  - if [ ! -d "$FLUTTER_PATH" ]; then git clone https://github.com/flutter/flutter.git -b $FLUTTER_CHANNEL $FLUTTER_PATH --depth 1; fi
  - export PATH="$FLUTTER_PATH/bin:$PATH"
  - flutter --version

test:
  stage: test
  tags:
    - ubuntu
    - macos
  environment:
    name: frontend-ci
  script:
    - flutter pub get
    - flutter analyze

build_android:
  stage: build
  tags:
    - ubuntu
  needs: ["test"]
  script:
    - flutter pub get
    - flutter test
    - flutter build apk
    - flutter build appbundle

build_ios:
  stage: build
  tags:
    - macos
  needs: ["test"]
  before_script:
    - export PATH="$FLUTTER_PATH/bin:$PATH"
  script:
    - flutter pub get
    - flutter test
    - flutter build ios --release --no-codesign

build_web:
  stage: build
  tags:
    - ubuntu
  needs: ["test"]
  script:
    - flutter pub get
    - flutter test
    - flutter build web