stages:
  - test
  - build

variables:
  FLUTTER_CHANNEL: stable
  FLUTTER_VERSION: 3.22.2
  FLUTTER_PATH: "/usr/local/flutter"

before_script:
  # Install dependencies and Flutter
  - apt-get update && apt-get install -y curl git unzip xz-utils libglu1-mesa
  - if [ ! -d "$FLUTTER_PATH" ]; then git clone https://github.com/flutter/flutter.git -b $FLUTTER_CHANNEL $FLUTTER_PATH --depth 1; fi
  - export PATH="$FLUTTER_PATH/bin:$PATH"
  - flutter --version

test:
  stage: test
  image: ubuntu:latest
  environment:
    name: frontend-ci
  script:
    - flutter pub get
    - flutter analyze

build_android:
  stage: build
  image: ubuntu:latest
  needs: ["test"]
  script:
    - flutter pub get
    - flutter test
    - flutter build apk
    - flutter build appbundle

build_ios:
  stage: build
  image: macos:latest
  needs: ["test"]
  before_script:
    - export PATH="$FLUTTER_PATH/bin:$PATH"
  script:
    - flutter pub get
    - flutter test
    - flutter build ios --release --no-codesign

build_web:
  stage: build
  image: ubuntu:latest
  needs: ["test"]
  script:
    - flutter pub get
    - flutter test
    - flutter build web

# Debugging steps
debug_info:
  stage: .pre
  script:
    - echo "Current PATH: $PATH"
    - echo "Flutter path: $FLUTTER_PATH"
    - flutter --version
    - flutter doctor