stages:
  - setup
  - test
  - build

only:
  - pushes
  - tags

setup:
  stage: setup
  tags:
    - ubuntu
  script:
    - unzip -o sdk-tools-linux.zip -d $ANDROID_HOME
    - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --licenses --sdk_root=$ANDROID_HOME || true
    - $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" --sdk_root=$ANDROID_HOME

test:
  stage: test
  tags:
    - ubuntu
  environment:
    name: frontend-ci
  script:
    - flutter pub get
    - flutter analyze

build_android:
  stage: build
  tags:
    - ubuntu
  needs: ["test"]
  script:
    - flutter pub get
    - flutter test
    - flutter build apk