name: bakingup_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ^3.22.2

dependencies:
  build_runner: ^2.4.11
  firebase_auth: ^4.6.2
  firebase_messaging: ^14.9.4
  firebase_core: ^2.32.0
  flutter_platform_alert: ^0.5.3
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - .env