import 'package:flutter/material.dart';

Color beigeColor = const Color(0xFFF4E3D8);
Color brownColor = const Color(0xFF5D4037);
Color pinkColor = const Color(0xFFFFEEEE);
Color redColor = const Color(0xFFE93935);
Color lightRedColor = const Color(0xFFF8C8C8);
Color greenColor = const Color(0xFF388E3C);
Color blackColor = const Color(0xFF000000);
Color yellowColor = const Color(0xFFFFBC3A);
Color dartYellowColor = const Color.fromARGB(255, 216, 158, 41);
Color lightYellowColor = const Color(0xFFFFECB3);
Color greyColor = const Color(0xFFD9D9D9);
Color whiteColor = const Color(0xFFFFFFFF);
Color lightGreyColor = const Color(0xFFEDEDED);
Color darkGreyColor = const Color(0xFF858585);
Color lightGreenColor = const Color(0xFFC8E6C9);
Color backgroundColor = const Color(0xFFFDFDFD);
Color orangeColor = const Color(0xFFDC6E46);
Color darkBeigeColor = const Color(0xFFE0C3B3);
Color darkBrownColor = const Color(0xFF5D4037);
Color errorLightRedColor = const Color(0xFFF8C8C8);
Color errorRedColor = const Color(0xFFD80808);
Color blueColor = const Color(0xFF0D6EFF);
Color lightPinkColor = const Color(0xFFFFCDD2);
Color greenRangeCalendar = const Color(0xFFC8E6C9);
