name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: frontend-ci

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Create .env
        run: |
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" > .env
      - name: Set up Flutter and test
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze

  build_android:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Create .env
        run: |
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" > .env
      - name: Set up Flutter and build APK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle

  build_ios:
    runs-on: macos-latest
    needs: [test]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Create .env
        run: |
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" > .env
      - name: Set up Flutter and build iOS
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --release --no-codesign